---
- name: deploy
  hosts: all
  gather_facts: false
  become: true
  tasks:

    # - name: create user
    #   user: 
    #     name: bane
    #     state: present
    #     shell: /bin/bash
    #     password: "{{ 'bane' | password_hash('sha512') }}"
    #     update_password: on_create

    # - name: sshd password
    #   lineinfile:
    #     path: /etc/ssh/sshd_config
    #     regexp: '^PasswordAuthentication '
    #     insertafter: '#PasswordAuthentication'
    #     line: 'PasswordAuthentication yes'
    #   notify: restart_sshd

    # - name: sudo
    #   copy:
    #    dest: /etc/sudoers.d/bane
    #    content: "bane ALL=(root) NOPASSWD: ALL"

    - name: Log into ghcr
      docker_login:
        registry: ghcr.io
        username: mirosavljevbranislav
        password: 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

    - name: pull webshop image
      docker_image:
        name: ghcr.io/mirosavljevbranislav/webshop:latest
        
  # handlers:
  #   - name: restart_sshd
  #     service:
  #       name: sshd
  #       state: restarted
